---
#Simple Ansible Playbook to build and push Docker image to Registry
 
- name: Playbook to build and run Docker
  hosts: ansibleserver
  #become: true
  gather_facts: false
 
  tasks:

    - name: Push Docker image to Registry
      docker_image:
        name: simple-nginx-image
        build:
          path: /opt/docker2
          pull: true
        state: present
        tag: "latest"
        force_tag: yes
        repository: dubbaka/simple-nginx-image:latest
        push: yes
        source: build
