---
# tasks file for tomcat
- name: updates registry.
  become: true
  apt:
    update_cache: yes

- name: install JAVA.
  apt:
    pkg: default-jdk
    state: latest
    update_cache: true

- name: add tomcat group.
  group:
    name: tomcat
    state: present

- name: add tomcat user.
  user:
    name: tomcat
    create_home: yes
    groups: tomcat

- name: create software directory.
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755
    recurse: yes

- name: download and unzip software.
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.68/bin/apache-tomcat-9.0.68.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts : [--strip-components=1]

- name: Copy tomcat service file.
  copy:
    src: "{{ role_path }}/files/tomcat.service"
    dest:  /etc/systemd/system/tomcat.service

- name: Change ownership and permission of tomcat directory.
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755
    recurse: yes

- name: Start and Enable tomcat
  systemd:
    name: tomcat
    state: started
    daemon_reload: true



