apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo 
    spec:
      containers: 
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
              hostPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          PersistentVolumeClaim:
            claimName: pvc-mongo-data

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  selector:
    app: mongo
  ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017