apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo-data
spec:
  accessModes:
    - ReadWriteOnce 
  volumeName: pv-mongo-data
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo 
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-mongo-data
      containers: 
        - name: mongo
          image: mongo
          volumeMounts:
            - name: storage
              mountPath: /data/db

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
  externalIPs:
    - 192.168.1.212
    - 192.168.1.213
    - 192.168.1.215

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: devopsedu/employee
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  externalIPs:
    - 192.168.1.212
  