apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: devopsedu/employee
          ports:
            - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  externalIPs:
    - 192.168.1.212
  