apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: edureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: pulakdocker/mongo
        name: mongo

---
apiVersion: v1
kind: Service
metadata:
   name: mongo
   namespace: edureka
spec:
   type: ClusterIP
   ports:
    - port: 27017
   selector:
     app: mongodb
   externalIPs:
     - 192.168.1.212
     - 192.168.1.213
     - 192.168.1.215

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: edureka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: pulakdocker/springboot-mongo-app
        name: springboot-mongo-app

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: edureka
spec:
  type: NodePort
  ports:
   - port: 8080
  selector:
    app: myapp
  externalIPs:
    - 192.168.1.212
    - 192.168.1.213
    - 192.168.1.215